version: '3'
services:
  server:
    build: 
      context: .
      args:
        ENV: ${ENV}
    restart: unless-stopped
    env_file:
      - envs/${ENV}.env
    volumes:
      - ./:/app:cached
      - /app/node_modules
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    working_dir: /app
    profiles:
      - dev
      - prod
  nginx:
    build: ./nginx
    env_file:
      - envs/${ENV}.env
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certs/${ENV}:/etc/nginx/ssl
    profiles:
      - dev
      - prod
    depends_on:
      - server
  letsencrypt:
    env_file:
      - envs/${ENV}.env
    image: nginxproxy/acme-companion:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/prod:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx
    profiles:
      - prod
volumes:
  mongodata:
