version: '3'
services:
  server:
    build: 
      context: .
      args:
        ENV: ${ENV}
    restart: unless-stopped
    container_name: geptyro-io-${ENV}-server
    env_file:
      - ../envs/${ENV}.env
    volumes:
      - ./:/app:cached
      - ../build:/etc/build
      - /app/node_modules
      - ./nginx/${ENV}/certs:/etc/nginx/certs
    expose:
      - "${EXPRESS_PORT}"
    working_dir: /app
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=${EXPRESS_PORT}
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=geptyro@gmail.com
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: geptyro-io-${ENV}-nginx-proxy
    env_file:
      - ../envs/${ENV}.env
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/${ENV}/certs:/etc/nginx/certs
      - ./nginx/${ENV}/vhost:/etc/nginx/vhost.d
      - ./nginx/${ENV}/html:/usr/share/nginx/html
  # Let's Encrypt companion for automatic SSL certificates
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: geptyro-io-${ENV}-letsencrypt
    env_file:
      - ../envs/${ENV}.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/${ENV}/certs:/etc/nginx/certs
      - ./nginx/${ENV}/vhost:/etc/nginx/vhost.d
      - ./nginx/${ENV}/html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=geptyro-io-${ENV}-nginx-proxy
      - LETSENCRYPT_STAGING=1
      - LETSENCRYPT_ENV=staging
  database:
    restart: unless-stopped
    container_name: geptyro-io-${ENV}-database
    image: mongo:4.2.18 # Version used on our MongoAtlas cluster
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: