version: '3'
services:
  server:
    build: 
      context: .
      args:
        ENV: ${ENV}
    restart: unless-stopped
    container_name: geptyro-io-${ENV}-server
    env_file:
      - ../envs/${ENV}.env
    volumes:
      - ./:/app:cached
      - ../build:/etc/build
      - /app/node_modules
    expose:
      - "${EXPRESS_PORT}"
    working_dir: /app
    environment:
      - VIRTUAL_HOST=${HOST},www.${HOST}
      - VIRTUAL_PORT=${EXPRESS_PORT}
      - LETSENCRYPT_HOST=${HOST},www.${HOST}
      - LETSENCRYPT_EMAIL=geptyro@gmail.com
    networks:
      - sools-nginx
      - geptyro.io-prod
  database:
    restart: unless-stopped
    container_name: geptyro-io-${ENV}-database
    image: mongo:4.2.18 # Version used on our MongoAtlas cluster
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
    networks:
      - geptyro.io-prod
volumes:
  mongodata:
networks:
  sools-nginx:
    external: true
  geptyro.io-prod: