version: '3'
services:
  database:
    restart: unless-stopped
    container_name: geptyro-io-${ENV}-database
    image: mongo:4.2.18 # Version used on our MongoAtlas cluster
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: